version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/build"
    schedule:
      interval: "weekly"
