//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("3745F3DA-6ABB-4C58-923D-B09E4A04688F")]
[assembly: AssemblyTitle("Machine.Fakes (cadef6)")]
[assembly: AssemblyDescription("Generic faking capabilites on top of Machine.Specifications")]
[assembly: AssemblyProduct("Machine.Fakes (cadef6)")]
[assembly: AssemblyCopyright("Copyright - Machine.Fakes 2011")]
[assembly: AssemblyVersion("0.0.2.0")]
[assembly: AssemblyFileVersion("0.0.2.0")]
[assembly: AssemblyDelaySign(false)]


